## ro.gemspec
#

Gem::Specification::new do |spec|
  spec.name = "ro"
  spec.version = "4.4.1"
  spec.required_ruby_version = '>= 3.0'
  spec.platform = Gem::Platform::RUBY
  spec.summary = "all your content in github, as god intended"
  spec.description = "the worlds tiniest, bestest, most minmialist headless cms - powered by github\n\nro is a minimalist toolkit for managing heterogeneous collections of rich web\ncontent on github, and providing both programatic and api access to it with zero\nheavy lifting"
  spec.license = "Nonstandard"

  spec.files =
["Gemfile",
 "Gemfile.lock",
 "LICENSE",
 "README.md",
 "README.md.erb",
 "Rakefile",
 "bin",
 "bin/ro",
 "lib",
 "lib/ro",
 "lib/ro.rb",
 "lib/ro/_lib.rb",
 "lib/ro/asset.rb",
 "lib/ro/collection",
 "lib/ro/collection.rb",
 "lib/ro/collection/list.rb",
 "lib/ro/config.rb",
 "lib/ro/error.rb",
 "lib/ro/html.rb",
 "lib/ro/html_safe.rb",
 "lib/ro/klass.rb",
 "lib/ro/methods.rb",
 "lib/ro/model.rb",
 "lib/ro/node.rb",
 "lib/ro/pagination.rb",
 "lib/ro/path.rb",
 "lib/ro/root.rb",
 "lib/ro/script",
 "lib/ro/script.rb",
 "lib/ro/script/builder.rb",
 "lib/ro/script/console.rb",
 "lib/ro/script/server.rb",
 "lib/ro/slug.rb",
 "lib/ro/template",
 "lib/ro/template.rb",
 "lib/ro/template/rouge_formatter.rb",
 "lib/ro/text.rb",
 "public",
 "public/api",
 "public/api/ro",
 "public/api/ro/index-1.json",
 "public/api/ro/index.json",
 "public/api/ro/nerd",
 "public/api/ro/nerd/fastest-possible-embeddings",
 "public/api/ro/nerd/fastest-possible-embeddings/index.json",
 "public/api/ro/nerd/ima",
 "public/api/ro/nerd/ima/index.json",
 "public/api/ro/nerd/index",
 "public/api/ro/nerd/index-1.json",
 "public/api/ro/nerd/index.json",
 "public/api/ro/nerd/index/index.json",
 "public/api/ro/pages",
 "public/api/ro/pages/about",
 "public/api/ro/pages/about/index.json",
 "public/api/ro/pages/contact",
 "public/api/ro/pages/contact/index.json",
 "public/api/ro/pages/cv",
 "public/api/ro/pages/cv/index.json",
 "public/api/ro/pages/disco",
 "public/api/ro/pages/disco/index.json",
 "public/api/ro/pages/index",
 "public/api/ro/pages/index-1.json",
 "public/api/ro/pages/index.json",
 "public/api/ro/pages/index/index.json",
 "public/api/ro/pages/jess",
 "public/api/ro/pages/jess/index.json",
 "public/api/ro/pages/now",
 "public/api/ro/pages/now/index.json",
 "public/api/ro/posts",
 "public/api/ro/posts/almost-died-in-an-ice-cave",
 "public/api/ro/posts/almost-died-in-an-ice-cave/index.json",
 "public/api/ro/posts/facebook-and-global-extremism",
 "public/api/ro/posts/facebook-and-global-extremism/index.json",
 "public/api/ro/posts/index-1.json",
 "public/api/ro/posts/index.json",
 "public/api/ro/posts/lemmings-considered-harmful",
 "public/api/ro/posts/lemmings-considered-harmful/index.json",
 "public/api/ro/posts/lost-in-the-desert",
 "public/api/ro/posts/lost-in-the-desert/index.json",
 "public/api/ro/posts/mission",
 "public/api/ro/posts/mission/index.json",
 "public/api/ro/posts/return-your-laptop",
 "public/api/ro/posts/return-your-laptop/index.json",
 "public/ro",
 "public/ro/nerd",
 "public/ro/nerd/fastest-possible-embeddings",
 "public/ro/nerd/fastest-possible-embeddings/assets",
 "public/ro/nerd/fastest-possible-embeddings/assets/giraffe.jpeg",
 "public/ro/nerd/fastest-possible-embeddings/assets/let-me-in.jpg",
 "public/ro/nerd/fastest-possible-embeddings/assets/src",
 "public/ro/nerd/fastest-possible-embeddings/assets/src/fastembed.js",
 "public/ro/nerd/fastest-possible-embeddings/assets/src/fastembed.rs",
 "public/ro/nerd/fastest-possible-embeddings/assets/terminal.jpg",
 "public/ro/nerd/fastest-possible-embeddings/attributes.yml",
 "public/ro/nerd/fastest-possible-embeddings/body.md",
 "public/ro/nerd/ima",
 "public/ro/nerd/ima/assets",
 "public/ro/nerd/ima/assets/og.jpeg",
 "public/ro/nerd/ima/attributes.yml",
 "public/ro/nerd/ima/body.md",
 "public/ro/nerd/index",
 "public/ro/nerd/index/assets",
 "public/ro/nerd/index/assets/giraffe.jpeg",
 "public/ro/nerd/index/assets/let-me-in.jpg",
 "public/ro/nerd/index/assets/terminal.jpg",
 "public/ro/nerd/index/attributes.yml",
 "public/ro/nerd/index/body.md",
 "public/ro/pages",
 "public/ro/pages/about",
 "public/ro/pages/about/assets",
 "public/ro/pages/about/assets/og.jpeg",
 "public/ro/pages/about/assets/speak-english-pulp-fiction.gif",
 "public/ro/pages/about/body.md",
 "public/ro/pages/contact",
 "public/ro/pages/contact/assets",
 "public/ro/pages/contact/assets/giraffe.jpeg",
 "public/ro/pages/contact/attributes.yml",
 "public/ro/pages/contact/body.md",
 "public/ro/pages/cv",
 "public/ro/pages/cv/assets",
 "public/ro/pages/cv/assets/ara.jpg",
 "public/ro/pages/cv/attributes.yml",
 "public/ro/pages/cv/body.md",
 "public/ro/pages/disco",
 "public/ro/pages/disco/assets",
 "public/ro/pages/disco/assets/disco.jpg",
 "public/ro/pages/disco/assets/disco.png",
 "public/ro/pages/disco/assets/speak-english-pulp-fiction.gif",
 "public/ro/pages/disco/assets/src",
 "public/ro/pages/disco/assets/src/environment.md",
 "public/ro/pages/disco/assets/src/fortune-500.md",
 "public/ro/pages/disco/assets/src/greed.md",
 "public/ro/pages/disco/assets/src/up-at-night.md",
 "public/ro/pages/disco/attributes.yml",
 "public/ro/pages/disco/body.md",
 "public/ro/pages/disco/samples",
 "public/ro/pages/disco/samples/environment.md",
 "public/ro/pages/disco/samples/fortune-500.md",
 "public/ro/pages/disco/samples/greed.md",
 "public/ro/pages/disco/samples/up-at-night.md",
 "public/ro/pages/index",
 "public/ro/pages/index/attributes.yml",
 "public/ro/pages/index/body.md",
 "public/ro/pages/jess",
 "public/ro/pages/jess/assets",
 "public/ro/pages/jess/assets/og.jpg",
 "public/ro/pages/jess/assets/speak-english-pulp-fiction.gif",
 "public/ro/pages/jess/attributes.yml",
 "public/ro/pages/jess/body.md",
 "public/ro/pages/now",
 "public/ro/pages/now/assets",
 "public/ro/pages/now/assets/speak-english-pulp-fiction.gif",
 "public/ro/pages/now/attributes.yml",
 "public/ro/pages/now/body.md",
 "public/ro/posts",
 "public/ro/posts/almost-died-in-an-ice-cave",
 "public/ro/posts/almost-died-in-an-ice-cave/assets",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image1.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image10.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image11.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image12.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image13.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image14.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image15.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image2.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image3.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image4.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image5.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image6.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image7.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image8.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/image9.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/josh-pointing.jpg",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/levi-rawr.png",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/og.jpg",
 "public/ro/posts/almost-died-in-an-ice-cave/assets/purple-heart.jpg",
 "public/ro/posts/almost-died-in-an-ice-cave/attributes.yml",
 "public/ro/posts/almost-died-in-an-ice-cave/body.md",
 "public/ro/posts/facebook-and-global-extremism",
 "public/ro/posts/facebook-and-global-extremism/assets",
 "public/ro/posts/facebook-and-global-extremism/assets/background.html",
 "public/ro/posts/facebook-and-global-extremism/assets/background.md",
 "public/ro/posts/facebook-and-global-extremism/assets/og.jpg",
 "public/ro/posts/facebook-and-global-extremism/assets/prompt.txt",
 "public/ro/posts/facebook-and-global-extremism/assets/results.md",
 "public/ro/posts/facebook-and-global-extremism/assets/survey.txt",
 "public/ro/posts/facebook-and-global-extremism/attributes.yml",
 "public/ro/posts/facebook-and-global-extremism/body.md",
 "public/ro/posts/lemmings-considered-harmful",
 "public/ro/posts/lemmings-considered-harmful/assets",
 "public/ro/posts/lemmings-considered-harmful/assets/lemming.jpeg",
 "public/ro/posts/lemmings-considered-harmful/attributes.yml",
 "public/ro/posts/lemmings-considered-harmful/body.md",
 "public/ro/posts/lost-in-the-desert",
 "public/ro/posts/lost-in-the-desert/assets",
 "public/ro/posts/lost-in-the-desert/assets/og.jpg",
 "public/ro/posts/lost-in-the-desert/attributes.yml",
 "public/ro/posts/lost-in-the-desert/body.md",
 "public/ro/posts/mission",
 "public/ro/posts/mission/assets",
 "public/ro/posts/mission/assets/og.jpg",
 "public/ro/posts/mission/attributes.yml",
 "public/ro/posts/mission/body.md",
 "public/ro/posts/return-your-laptop",
 "public/ro/posts/return-your-laptop/assets",
 "public/ro/posts/return-your-laptop/assets/og.jpg",
 "public/ro/posts/return-your-laptop/assets/return-your-laptop.png",
 "public/ro/posts/return-your-laptop/attributes.yml",
 "public/ro/posts/return-your-laptop/body.md",
 "ro.gemspec",
 "scripts",
 "scripts/speedtest.rb",
 "tmp/gem-details.oe"]

  spec.executables = ["ro"]
  
  spec.require_path = "lib"

  
    spec.add_dependency(*["map", "~> 6.6", ">= 6.6.0"])
  
    spec.add_dependency(*["kramdown", "~> 2.4", " >= 2.4.0"])
  
    spec.add_dependency(*["kramdown-parser-gfm", "~> 1.1", " >= 1.1.0"])
  
    spec.add_dependency(*["rouge", "~> 4.1", " >= 4.1.1"])
  
    spec.add_dependency(*["front_matter_parser", "~> 1.0"])
  
    spec.add_dependency(*["rinku", "~> 2.0"])
  
    spec.add_dependency(*["image_size", "~> 3.4"])
  
    spec.add_dependency(*["nokogiri", "~> 1"])

    spec.add_dependency(*["webrick", "~> 1.9", ">= 1.9.1"])

  spec.extensions.push(*[])

  spec.author = "Ara T. Howard"
  spec.email = "ara.t.howard@gmail.com"
  spec.homepage = "https://github.com/ahoward/ro"
end
